export enum EventType {
    INGESTION_COMPLETED = 'INGESTION_COMPLETED',
    INGESTION_FAILED = 'INGESTION_FAILED',
    FINDING_STATUS_CHANGED = 'FINDING_STATUS_CHANGED',
    AI_ANALYSIS_REQUESTED = 'AI_ANALYSIS_REQUESTED',
    AI_ANALYSIS_COMPLETED = 'AI_ANALYSIS_COMPLETED',
    AI_ANALYSIS_FAILED = 'AI_ANALYSIS_FAILED',
    REACHABILITY_COMPUTED = 'REACHABILITY_COMPUTED', // Legacy? Kept for safety
    GRAPH_BUILD_REQUESTED = 'GRAPH_BUILD_REQUESTED',
    GRAPH_BUILD_COMPLETED = 'GRAPH_BUILD_COMPLETED',
    GRAPH_BUILD_FAILED = 'GRAPH_BUILD_FAILED',
    AI_TOGGLED = 'AI_TOGGLED',
    TI_TOGGLED = 'TI_TOGGLED',

    // Task 4.7 - Live Intelligence Plane
    DEPENDENCY_SWEEP_REQUESTED = 'DEPENDENCY_SWEEP_REQUESTED',
    DEPENDENCY_SWEEP_COMPLETED = 'DEPENDENCY_SWEEP_COMPLETED',
    DEPENDENCY_SWEEP_FAILED = 'DEPENDENCY_SWEEP_FAILED',
    FINDING_OVERRIDE_SET = 'FINDING_OVERRIDE_SET',
    FINDING_OVERRIDE_CLEARED = 'FINDING_OVERRIDE_CLEARED',
    SESSION_STARTED = 'SESSION_STARTED'
}

export interface AppEvent {
    id: string;         // UUID
    type: EventType;
    sessionId: string;  // Associated Session
    timestamp: number;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    payload: Record<string, any>; // Flexible structured data
}
